### ISSUE TITLE
Following the instructions in the document getting errors during push

### ISSUE THREAD

**Issue by donaldrivard** [reidaelliott/sfdxAnalyticsQuickStart#2]
running sfdx force:source:push I get the error: 

Unexpected file found in package directory: /Users/drivard/analytics/sfdxAnalyticsQuickStart/force-app/main/default/waveTemplates/Mortgage_Calculator/template-info.json.

Is there another step?

Don

**Comment by reidaelliott** [comment]
what do you see when you run 'sfdx --version'
I am guessing you had installed the CLI previously and may need to update?

**Comment by donaldrivard** [comment]
sfdx-cli/6.34.0-6fec0d751a (darwin-x64) node-v8.9.4

I did run sfdx:update
sfdx-cli: Updating CLI... already on latest version: 6.34.0-6fec0d751a

**Comment by reidaelliott** [comment]
Ok, that is right.  Do you know what server instance you're dev hub is on?  We had to make a few server side changes and we're in a staggered release window right now where about only 1/2 the servers are updated, so the necessary server changes for analytics templates are likely not there.  All servers should be update by October 13.  Are you interested in me getting you a temporary dev hub on an updated instance to authenticate too and try this out?

**Comment by donaldrivard** [comment]
My Org ID is 00D300000000S3f. As for the temp dev hub I can wait until the 13th. I saw Skips tweet and the plugin looks very interesting. I have only created a couple of Analytics Templates/Apps in the past using the RestAPI but I am a big fan of the cli and was just taking a bit this morning to play around. Thanks again for the quick response!

**Comment by reidaelliott** [comment]
looking back this should work in both versions.  could you report back what you get by running 

sfdx plugins --core

**Comment by donaldrivard** [comment]
Here you go:

sfdx plugins --core
@amphro/streamer 1.0.0
@salesforce/analytics 0.1.0
@salesforce/plugin-generator 0.0.10 (core)
@salesforce/sfdx-trust 1.0.8 (core)
builtins 1.0.0 (core)
salesforcedx 42.4.0 (42.4.0)
sfdx-falcon 0.0.8
sfdx-vscode 0.0.0 (link)
shane-sfdx-plugins 0.33.1

**Comment by reidaelliott** [comment]
All looks good but you salesforcedx is behind.  Mine with latest installer is salesforcedx 43.17.0 (core)
I thought sfdx update would do this.  Maybe you installed via npm?

https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_update_cli.htm

I can ask around if we can't figure out how to get this updated.

**Comment by donaldrivard** [comment]
I do not believe that I did use npm (been a long time). However I run sfdx update almost everyday to check. I have been updated in the past as I have had the cli installed on this machine for a while.

**Comment by reidaelliott** [comment]
Not sure why this won't update.  Your best bet may just be to uninstall and reinstall the cli: 

https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm

This will get rid of the plugins too so would need to reinstall them too, but shouldn't take much time and you'd be at a clean state.  There may have been some issues when they moved from heroku version 42 to 43.  I have checked internally if any other suggestions.

**Comment by donaldrivard** [comment]
uninstall/reinstall fixed the issue. I am now at:

@salesforce/plugin-generator 0.0.10 (core)
@salesforce/sfdx-trust 1.0.8 (core)
builtins 1.0.0 (core)
salesforcedx 43.17.0 (core)

sfdx force:source:push was successful. 
Thanks!

**Comment by reidaelliott** [comment]
great.  next thing I was going to suggest too was running sfdx plugins:update (maybe you already did).  Anyhow glad its working past this now.
