### ISSUE TITLE
Update the readme so they know that analytics is included by default in SFDX now

### ISSUE THREAD

**Issue by geoffrothman** [reidaelliott/sfdxAnalyticsQuickStart#3]
@reidaelliott they don't need to do the sfdx plugins:install @salesforce/analytics piece anymore right?

**Comment by reidaelliott** [comment]
The analytics commands are not part of the sfdx cli by default. Users will need to run this command to get the "analytics" top level topic available in the SFDX CLI

**Comment by geoffrothman** [comment]
> The analytics commands are not part of the sfdx cli by default. Users will need to run this command to get the "analytics" top level topic available in the SFDX CLI

wow didnt know that tks!! will they ever be included or will cloud specific utils always be from a plugin? @reidaelliott

**Comment by reidaelliott** [comment]
I believe the idea is to have platform specific functionality standard, but cloud specific utils will come from plugins.  Analytics was one of the first in-house SFDC developed plugins, and it will be fully supported by Salesforce.
